---
apiVersion: v1
kind: Service
metadata:
  name: svc
  labels:
    service: svc
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
  selector:
    service: svc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: svc
  labels:
    service: svc
spec:
  replicas: 3
  selector:
    matchLabels:
      service: svc
  template:
    metadata:
      labels:
        service: svc
    spec:
      containers:
        - name: main
          image: ${modules["container"].outputs.deployment-image-id}
          imagePullPolicy: "Always"
          ports:
            - name: http
              containerPort: 8080
